### ISSUE TITLE
Start char and end char diff does not match entity length? 

### ISSUE THREAD

**Issue by lucy3** [ahalterman/mordecai3#12]
Hi, here's an output that I got from mordecai3: 

```
{
'doc_text': "The WDKS Crew The We Don't Know Sports guys all grew up in West Virginia, loving all things sports.", 
'event_location_raw': '', 
'geolocated_ents': [{'feature_code': 'ADM1', 'feature_class': 'A', 'country_code3': 'USA', 'lat': 38.50038, 'lon': -80.50009, 'name': 'West Virginia', 'admin1_code': 'WV', 'admin1_name': 'West Virginia', 'admin2_code': '', 'admin2_name': '', 'geonameid': '4826850', 'score': 1.0, 'search_name': 'West Virginia', 'start_char': 59, 'end_char': 77, 'city_id': '', 'city_name': ''}]
}
```

The `search_name` here is 'West Virginia', which has 13 characters, but the difference between `end_char` and `start_char` is much larger. Am I interpreting these keys incorrectly?

**Comment by ahalterman** [comment]
Good catch! [Here's](https://github.com/ahalterman/mordecai3/blob/bb05976f03d543b2b57543c5fb1dada8b5787247/mordecai3/geoparse.py#L136) where the bug is.

I define it as `"end_char": ent[-1].idx + len(ent.text)}`, but it should be `"end_char": ent[-1].idx + len(ent[-1].text)}`. Basically, I'm adding the whole length of the entity to the start position of the entity's final token, rather than just the length of the final token.
